"""initial_schema

Revision ID: 415fdc2ae1e8
Revises: 
Create Date: 2026-09-17 01:39:24.213363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415fdc2ae1e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('records_found', sa.Integer(), nullable=False),
    sa.Column('records_added', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_runs_source'), ['source'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)

    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_name'), ['name'], unique=False)

    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitors_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitors_id'), ['id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('engagement_count', sa.Integer(), nullable=False),
    sa.Column('engagement_velocity', sa.Float(), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_external_id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index('ix_posts_brand_published', ['brand_id', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_source'), ['source'], unique=False)
        batch_op.create_index('ix_posts_source_brand', ['source', 'brand_id'], unique=False)

    op.create_table('tracked_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracked_keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracked_keywords_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracked_keywords_id'), ['id'], unique=False)

    op.create_table('post_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('competitor', sa.String(length=255), nullable=True),
    sa.Column('key_positive', sa.Text(), nullable=True),
    sa.Column('key_negative', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('virality_score', sa.Float(), nullable=False),
    sa.Column('virality_level', sa.String(length=50), nullable=False),
    sa.Column('is_viral', sa.Boolean(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('analysis_version', sa.String(length=50), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_analysis_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_analysis_is_viral'), ['is_viral'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_analysis_post_id'), ['post_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_post_analysis_sentiment'), ['sentiment'], unique=False)
        batch_op.create_index('ix_post_analysis_sentiment_viral', ['sentiment', 'is_viral'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_analysis_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_analysis_virality_score'), ['virality_score'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_analysis_virality_score'))
        batch_op.drop_index(batch_op.f('ix_post_analysis_topic'))
        batch_op.drop_index('ix_post_analysis_sentiment_viral')
        batch_op.drop_index(batch_op.f('ix_post_analysis_sentiment'))
        batch_op.drop_index(batch_op.f('ix_post_analysis_post_id'))
        batch_op.drop_index(batch_op.f('ix_post_analysis_is_viral'))
        batch_op.drop_index(batch_op.f('ix_post_analysis_id'))

    op.drop_table('post_analysis')
    with op.batch_alter_table('tracked_keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_keywords_id'))
        batch_op.drop_index(batch_op.f('ix_tracked_keywords_brand_id'))

    op.drop_table('tracked_keywords')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('ix_posts_source_brand')
        batch_op.drop_index(batch_op.f('ix_posts_source'))
        batch_op.drop_index(batch_op.f('ix_posts_published_at'))
        batch_op.drop_index(batch_op.f('ix_posts_id'))
        batch_op.drop_index(batch_op.f('ix_posts_content_hash'))
        batch_op.drop_index('ix_posts_brand_published')
        batch_op.drop_index(batch_op.f('ix_posts_brand_id'))

    op.drop_table('posts')
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitors_id'))
        batch_op.drop_index(batch_op.f('ix_competitors_brand_id'))

    op.drop_table('competitors')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_name'))
        batch_op.drop_index(batch_op.f('ix_brands_id'))

    op.drop_table('brands')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    with op.batch_alter_table('collection_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_runs_source'))
        batch_op.drop_index(batch_op.f('ix_collection_runs_id'))

    op.drop_table('collection_runs')
    # ### end Alembic commands ###
